# Generated by Django 2.2.24 on 2021-12-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='produto',
            new_name='nome_prod',
        ),
    ]
