# Generated by Django 2.2.24 on 2021-12-06 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cliente', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_produto', models.IntegerField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
