# Generated by Django 2.2.24 on 2021-12-06 03:47

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cpf',
            field=cpf_field.models.CPFField(default=1, max_length=14, verbose_name='cpf'),
            preserve_default=False,
        ),
    ]
