# Generated by Django 2.2.24 on 2021-12-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_venda_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='id_produto',
        ),
        migrations.AddField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loja.Produto'),
            preserve_default=False,
        ),
    ]
